#!/usr/bin/env bash

#install ruby
curl -L get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh
rvm reload
rvm install 2.1.0

#install capistrano
gem install capistrano

#edit sudoers
echo "%deployers ALL=(ALL:ALL) ALL" >> /etc/sudoers
