#!/usr/bin/env bash

#install ruby
curl -L get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh
rvm reload
rvm install 2.1.0

#install capistrano
gem install capistrano

#setup users
useradd -u 12345 -g users -d /home/deployer -s /bin/bash -p $(echo n493Kp71 | openssl passwd -1 -stdin) deployer
groupadd deployers
usermod -a -G deployers deployer
mkdir /home/deployer
chown deployer:deployers /home/deployer

# but still need to edit /etc/sudoers and add %deployers ALL=(ALL) ALL


