#!/usr/bin/env bash

# for debian/ubuntu
echo deb http://apt.newrelic.com/debian/ newrelic non-free >> /etc/apt/sources.list.d/newrelic.list
wget -O- https://download.newrelic.com/548C16BF.gpg | apt-key add -
apt-get update
apt-get install newrelic-sysmond
rsysmond-config --set license_key=$NEWRELIC_LICENSEKEY
/etc/init.d/newrelic-sysmond start
