#!/usr/bin/env bash

apt-get update
apt-get install git
apt-get install build-essential
#https://raw.githubusercontent.com/anonmily/scripts/master/new-server | bash
https://raw.githubusercontent.com/anonmily/scripts/master/nvm-node-install | bash

