#!/bin/bash

# Python scripting server with docker installed

apt-get -y update && apt-get -y install vim curl git build-essential apt-transport-https ca-certificates linux-image-extra-$(uname -r) linux-image-extra-virtual python python-pip

curl https://raw.githubusercontent.com/anonmily/scripts/master/docker-setup-ubuntu-16 | bash

curl -L https://github.com/docker/compose/releases/download/1.9.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
