#!/usr/bin/env bash

apacheuser=$1
currentuser=$(echo $(whoami))

adduser dev --disabled-password --gecos "DevUser","none","none","none"
groupadd www
usermod -a -G www dev
usermod -a -G www $currentuser
chown -R $apacheuser:www /var/www
chmod 2775 /var/www
find /var/www -type d -exec chmod 2775 {} +
find /var/www -type f -exec chmod 0664 {} +
