#!/usr/bin/env bash

currentuser=$(echo $(whoami))

adduser dev
groupadd www
usermod -a -G www dev
usermod -a -G www $currentuser
chown -R www-data:www /var/www
chmod 2775 /var/www
find /var/www -type d -exec chmod 2775 {} +
find /var/www -type f -exec chmod 0664 {} +
