#!/bin/bash
cd /tmp

apt-get -y update && \
apt-get -y install \
  git \
  curl \
  vim \
  python python-pip python-dev \
  build-essential make cmake \
  openssh-server \
  xsel \
  ufw
  
# Python-related
wget https://www.python.org/ftp/python/3.5.2/Python-3.5.2.tgz && \
tar xzf Python-3.5.2.tgz

# Pip packages
pip install virtualenv

# Install Ansible
apt-add-repository ppa:ansible/ansible && \
apt-get -y update && \
apt-get -y install \
  software-properties-common \
  ansible

# Install Virtualbox
echo "deb http://download.virtualbox.org/virtualbox/debian xenial contrib" > /etc/apt/sources.list.d/virtualbox.list && \
wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | apt-key add - && \
wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | apt-key add - && \
apt-get -y update && \
apt-get -y install dkms virtualbox-5.1

# Install Vagrant
wget https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb && \
dpkg -i vagrant_1.9.1_x86_64.deb && echo "Vagrant installed successfully."

# Install sublime text
wget https://download.sublimetext.com/sublime-text_build-3126_amd64.deb && \
dpkg -i sublime-text_build-3126_amd64.deb && echo "Sublime Text install successfully"

# Install Docker
apt-get -y purge lxc-docker*
apt-get -y purge docker.io*
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D && \
echo "deb https://apt.dockerproject.org/repo ubuntu-$(lsb_release -ic | tail -n 1 | awk '{print $2}') main" > /etc/apt/sources.list.d/docker.list && \
apt-get -y install apt-transport-https linux-image-extra-$(uname -r) && \
apt-get -y update && \
apt-get -y install docker-engine && \
service docker start
groupadd docker
usermod -aG docker $(whoami)
curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

# Install NVM/NodeJS
#curl https://raw.githubusercontent.com/anonmily/scripts/master/nvm-node-install | bash

# Install OpenCV/ImageMagick
curl https://raw.githubusercontent.com/anonmily/scripts/master/opencv-imagemagick | bash
